version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: bank-rest-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
#     Проброс порта для внешнего подключения к БД, если оно не требуется, то порт лучше закрыть
      - "5000:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank-rest-service
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "4000:4000"
