### Transfer money between cards
PUT http://localhost:4000/client/transfer
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "sourceCardNumber": "1111 2222 3333 4444",
  "destinationCardNumber": "2222 2222 3333 4444",
  "amount": "15000"
}
###